window.LECTURES = [
  { id: 'Micro 1', min: 'TBA',  title: 'Economics and Economy', video: 'https://www.youtube.com/embed/ZYfdzVAdEGI', notes: '#', pyq: '#', progress: 1, teacher: 'Manish Sir' },
  { id: 'Micro 2', min: 'TBA',  title: 'Central Problems of an Economy', video: 'https://www.youtube.com/embed/7MWGayP7Fss', notes: '#', pyq: '#', progress: 1, teacher: 'Manish Sir' },
  { id: 'Micro 3', min: 'TBA',  title: "Consumer's Equilibrium - Utility Analysis", video: 'https://www.youtube.com/embed/e6VXKEczL-4', notes: '#', pyq: '#', progress: 1, teacher: 'Manish Sir' },
  { id: 'Micro 4', min: 'TBA',  title: 'Theory of Demand', video: 'https://www.youtube.com/embed/JaBff_VZiiw', notes: '#', pyq: '#', progress: 1, teacher: 'Manish Sir' },
  { id: 'Micro 5', min: 'TBA',  title: 'Price Elasticity of Demand', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 6', min: 'TBA',  title: 'Production Function and Returns to a Factor', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 7', min: 'TBA',  title: 'Concept of Cost', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 8', min: 'TBA',  title: 'Concept of Revenue', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 9', min: 'TBA',  title: "Producer's Equilibrium", video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 10', min: 'TBA',  title: 'Theory of Supply', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 11', min: 'TBA',  title: 'Forms of Market', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Micro 12', min: 'TBA',  title: 'Market Equilibrium', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'Manish Sir' },
  { id: 'Macro 1', min: 'TBA', title: 'Introduction to Macroeconomics', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Manish Sir' },
  { id: 'Macro 2', min: 'TBA', title: 'Some Basic Concepts of Macroeconomics', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Ms. Y' },
  { id: 'Macro 3', min: 'TBA', title: 'National Income and Related Aggregates', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Mr. Z' },
  { id: 'Macro 4', min: 'TBA', title: 'Methods of Calculating National Income', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Manish Sir' },
  { id: 'Macro 5', min: 'TBA', title: 'Money and Banking', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Ms. Y' },
  { id: 'Macro 6', min: 'TBA', title: 'Aggregate Demand, Supply and Related Concepts', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Mr. Z' },
  { id: 'Macro 7', min: 'TBA', title: 'Short Run Equilibrium Output', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Manish Sir' },
  { id: 'Macro 8', min: 'TBA', title: 'Problem of Deficient and Excess Demand', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Ms. Y' },
  { id: 'Macro 9', min: 'TBA', title: 'Government Budget and the Economy', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Mr. Z' },
  { id: 'Macro 10', min: 'TBA', title: 'Foreign Exchange Rate', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Manish Sir' },
  { id: 'Macro 11', min: 'TBA', title: 'Balance of Payments', video: '', notes: '#', pyq: '#', progress: 0.0, teacher: 'Ms. Y' },
];