window.LECTURES = [
{ id: 'EN1', min:'TBA', title: 'Synonyms', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN2', min:'TBA', title: 'Idioms and Phrases', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN3', min:'TBA', title: 'English Vocabulary 1', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN4', min:'TBA', title: 'Tenses and Voices', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN5', min:'TBA', title: 'Voice', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN6', min:'TBA', title: 'Parts of Speech', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN7', min:'TBA', title: 'Phrasal Verb', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN8', min:'TBA', title: 'Modals', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN9', min:'TBA', title: 'Question Tags', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN10', min:'TBA', title: 'Preposition', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN11',  min:'TBA',title: 'Direct & Indirect Speech', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN12',  min:'TBA',title: 'Vocabulary Booster', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN13',  min:'TBA',title: 'Foreign Words 1', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN14',  min:'TBA',title: 'Foreign Words 2', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN15',  min:'TBA',title: 'Conjunction', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN16',  min:'TBA',title: 'Determiners', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN17',  min:'TBA',title: 'Homonyms', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
  { id: 'EN18',  min:'TBA',title: 'Synonyms & Antonyms', video: 'soon.html', notes: '#', pyq: '#', progress: 0, teacher: 'English Sir' },
];
