export const APP = {
    NAME: "Asprients",
    VERSION: "2.1.9",
    UPCOMING: "2.2.0",
    RELEASE: "Major Update",
    TYPE: "Stable",
    UPDATE: " August 06 2026",
    FEATURES: 25,
    IMPROVEMENTS: 15,
    BUGS: 8,
    RELEASES: 5,
    SECURITY: "Security Upgrade",
    SIZE: "Major Release",
    TERMS_VERSION: "1.2.0",
};